	_IMG_Linked_Version
	_IMG_LoadTyped_RW
	_IMG_Load
	_IMG_Load_RW
	_IMG_InvertAlpha
	_IMG_isBMP
	_IMG_isPNM
	_IMG_isXPM
	_IMG_isXCF
	_IMG_isPCX
	_IMG_isGIF
	_IMG_isJPG
	_IMG_isTIF
	_IMG_isPNG
	_IMG_isLBM
	_IMG_LoadBMP_RW
	_IMG_LoadPNM_RW
	_IMG_LoadXPM_RW
	_IMG_LoadXCF_RW
	_IMG_LoadPCX_RW
	_IMG_LoadGIF_RW
	_IMG_LoadJPG_RW
	_IMG_LoadTIF_RW
	_IMG_LoadPNG_RW
	_IMG_LoadTGA_RW
	_IMG_LoadLBM_RW
	_IMG_ReadXPMFromArray
